#!/usr/bin/env python3
"""Re-emit ``<sandbox>/.supabase/credentials.env`` from the running stack.

Use cases::

    # Regenerate the file after it was deleted, without rotating secrets.
    python skills/supabase-init/scripts/print_env.py

    # Stream the env to stdout (skip the file write — handy for shell sourcing).
    eval "$(python skills/supabase-init/scripts/print_env.py --stdout)"

    # Point at a non-default sandbox.
    python skills/supabase-init/scripts/print_env.py --sandbox-root /path

The source of truth is ``<sandbox>/.supabase/docker/.env`` — the file
``init.py`` mutated when it rotated secrets. We never re-derive keys here;
this script is purely a projection from that file.
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

DEFAULT_SANDBOX_ROOT = Path(__file__).resolve().parents[3]


class C:
    R = "\033[31m"
    G = "\033[32m"
    Y = "\033[33m"
    B = "\033[34m"
    OFF = "\033[0m"


def info(m: str) -> None:  print(f"{C.B}→{C.OFF} {m}", file=sys.stderr, flush=True)
def ok(m: str) -> None:    print(f"{C.G}✓{C.OFF} {m}", file=sys.stderr, flush=True)
def warn(m: str) -> None:  print(f"{C.Y}!{C.OFF} {m}", file=sys.stderr, flush=True)
def err(m: str) -> None:   print(f"{C.R}✗{C.OFF} {m}", file=sys.stderr, flush=True)


def parse_env_file(path: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, _, v = line.partition("=")
        out[k.strip()] = v.strip().strip('"').strip("'")
    return out


def stack_running(docker_dir: Path) -> bool:
    try:
        proc = subprocess.run(
            ["docker", "compose", "ps", "--quiet"],
            cwd=str(docker_dir),
            capture_output=True,
            text=True,
            check=True,
        )
    except (FileNotFoundError, subprocess.CalledProcessError):
        return False
    return bool(proc.stdout.strip())


def render_credentials(env: dict[str, str]) -> str:
    api_port = env.get("KONG_HTTP_PORT", "8000")
    db_port = env.get("POSTGRES_PORT", "5432")
    api_url = f"http://127.0.0.1:{api_port}"
    pg_pwd = env.get("POSTGRES_PASSWORD", "")
    db_url = f"postgres://postgres:{pg_pwd}@127.0.0.1:{db_port}/postgres"

    return (
        "# Generated by skills/supabase-init/scripts/print_env.py — do not edit by hand.\n"
        "# Source this file from per-project .env files, or read it directly.\n"
        "\n"
        f"SUPABASE_URL={api_url}\n"
        f"SUPABASE_ANON_KEY={env.get('ANON_KEY', '')}\n"
        f"SUPABASE_SERVICE_ROLE_KEY={env.get('SERVICE_ROLE_KEY', '')}\n"
        f"SUPABASE_JWT_SECRET={env.get('JWT_SECRET', '')}\n"
        f"SUPABASE_DB_URL={db_url}\n"
        f"SUPABASE_STUDIO_URL={api_url}\n"
        f"SUPABASE_DASHBOARD_USERNAME={env.get('DASHBOARD_USERNAME', 'supabase')}\n"
        f"SUPABASE_DASHBOARD_PASSWORD={env.get('DASHBOARD_PASSWORD', '')}\n"
    )


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--sandbox-root", type=Path, default=DEFAULT_SANDBOX_ROOT,
                   help=f"sandbox root (default: {DEFAULT_SANDBOX_ROOT})")
    p.add_argument("--stdout", action="store_true",
                   help="print to stdout instead of writing credentials.env "
                        "(useful with `eval $(... --stdout)`)")
    p.add_argument("--allow-stopped", action="store_true",
                   help="don't refuse if the stack is stopped — read the .env anyway")
    return p.parse_args()


def main() -> None:
    args = parse_args()
    sandbox_root: Path = args.sandbox_root.resolve()
    stack_dir = sandbox_root / ".supabase"
    docker_dir = stack_dir / "docker"
    env_path = docker_dir / ".env"

    if not env_path.exists():
        err(f"no docker/.env at {env_path} — run init.py first")
        sys.exit(1)

    if not stack_running(docker_dir):
        if args.allow_stopped:
            warn("stack is not running — emitting from .env anyway (--allow-stopped)")
        else:
            err("stack is not running. Either:")
            err("  • run `python skills/supabase-init/scripts/init.py` to bring it up, or")
            err("  • re-run with --allow-stopped to emit anyway.")
            sys.exit(2)

    env = parse_env_file(env_path)
    rendered = render_credentials(env)

    if args.stdout:
        sys.stdout.write(rendered)
        return

    creds = stack_dir / "credentials.env"
    creds.write_text(rendered)
    ok(f"wrote {creds}")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        err("interrupted")
        sys.exit(130)
